// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUi7-aoID4y4tc1c3kpDZ8vgUq5__abY',
    appId: '1:81826383063:web:d4ed506b8b30da70d69c92',
    messagingSenderId: '81826383063',
    projectId: 'jodofiofe',
    authDomain: 'jodofiofe.firebaseapp.com',
    databaseURL: 'https://jodofiofe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jodofiofe.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3fUne6BaDGnq0taUnqXh93Ts_WtxAo8',
    appId: '1:81826383063:ios:520f9d99d3fe0befd69c92',
    messagingSenderId: '81826383063',
    projectId: 'jodofiofe',
    databaseURL: 'https://jodofiofe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jodofiofe.appspot.com',
    iosClientId: '81826383063-2fi95696gjjjui3r906in4s9qjiedd1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
